# Filter stations according to a different parameter & Change names to English

### analysis of the station from: https://ims.gov.il/he/node/1949¶
##### sheet1 = rain_stations, name: meta data archive ims 1_1.xls

In [1]:
import pandas as pd

In [2]:
df_rain_stations = pd.read_excel('Data Base/meta data archive ims 1_1.xls',sheet_name='rain_stations') 
df_rain_stations.head()

,מספר התחנה,שם התחנה,שם התחנה בלועזית,סוג התחנה,קואורדינטות ברשת ישראל החדשה מזרח,קואורדינטות ברשת ישראל החדשה צפון,קואורדינטות אורך גיאוגרפיות E,קואורדינטות אורך גיאוגרפיות N,גובה מעל פני הים (מטר),תאריך הפתיחה,תאריך הסגירה,תקופת זמינות הנתונים
0,110010,ראש הנקרה תחנה משטרה,ROSH HA NIQRA POLICE,מאוישת,210180,777600,35.1051º,33.0937º,60,1924-09-01 00:00:00,1948-06-01 00:00:00,09/1933 - 05/1948
1,110021,ראש הנקרה,ROSH HANIQRA,אוטומאטית,210430,776160,35.1079º,33.0806º,10,2003-09-01 00:00:00,NaN,09/2007 -
2,110050,כפר ראש הנקרה,KEFAR ROSH HANIQRA,מאוישת,211090,776760,35.1149º,33.0861º,50,1949-09-01 00:00:00,NaN,09/1949 -
3,110100,שלומי - אל-בסה,SHELOMI - EL-BASSA,מאוישת,213750,775800,35.1434º,33.0775º,50,1946-02-01 00:00:00,1947-07-01 00:00:00,02/1946 - 05/1947
4,110150,בצת,BEZET,מאוישת,213200,775150,35.1375º,33.0716º,35,1953-09-01 00:00:00,1967-05-31 00:00:00,09/1953 - 05/1967

###  Change names to English

In [3]:
df_rain_stations=df_rain_stations.rename(columns={df_rain_stations.columns[0]: "station num",
                                                  df_rain_stations.columns[1]: "station name_He",
                                                  df_rain_stations.columns[2]:"station name",
                                                  df_rain_stations.columns[3]:"station type",
                                                  df_rain_stations.columns[4]:"Coordinates on the New Israel Mizrah network",
                                                  df_rain_stations.columns[5]: "Coordinates on the New Israel North network",
                                                 df_rain_stations.columns[6]:"E geographic longitude lon",
                                                 df_rain_stations.columns[7]:"N geographic longitude lat",
                                                 df_rain_stations.columns[8]:"Altitude above sea level (meters)",
                                                  df_rain_stations.columns[9]:"The opening date",
                                                  df_rain_stations.columns[10]:"The closing date",
                                                  df_rain_stations.columns[11]:"Data availability period"
                                                 })
df_rain_stations.head()

,station num,station name_He,station name,station type,Coordinates on the New Israel Mizrah network,Coordinates on the New Israel North network,E geographic longitude lon,N geographic longitude lat,Altitude above sea level (meters),The opening date,The closing date,Data availability period
0,110010,ראש הנקרה תחנה משטרה,ROSH HA NIQRA POLICE,מאוישת,210180,777600,35.1051º,33.0937º,60,1924-09-01 00:00:00,1948-06-01 00:00:00,09/1933 - 05/1948
1,110021,ראש הנקרה,ROSH HANIQRA,אוטומאטית,210430,776160,35.1079º,33.0806º,10,2003-09-01 00:00:00,NaN,09/2007 -
2,110050,כפר ראש הנקרה,KEFAR ROSH HANIQRA,מאוישת,211090,776760,35.1149º,33.0861º,50,1949-09-01 00:00:00,NaN,09/1949 -
3,110100,שלומי - אל-בסה,SHELOMI - EL-BASSA,מאוישת,213750,775800,35.1434º,33.0775º,50,1946-02-01 00:00:00,1947-07-01 00:00:00,02/1946 - 05/1947
4,110150,בצת,BEZET,מאוישת,213200,775150,35.1375º,33.0716º,35,1953-09-01 00:00:00,1967-05-31 00:00:00,09/1953 - 05/1967

### Change type

In [4]:
df_rain_stations.dtypes

station num                                      int64
station name_He                                 object
station name                                    object
station type                                    object
Coordinates on the New Israel Mizrah network     int64
Coordinates on the New Israel North network      int64
E geographic longitude lon                      object
N geographic longitude lat                      object
Altitude above sea level (meters)               object
The opening date                                object
The closing date                                object
Data availability period                        object
dtype: object


#### E geographic longitude lon                to float
#### N geographic longitude lat                 to float

#### The opening date                                to datetime64[ns]
#### The closing date                                  to datetime64[ns]

In [5]:

df_rain_stations['E geographic longitude lon'] = df_rain_stations['E geographic longitude lon'].str.rstrip('º').astype(float)
df_rain_stations['N geographic longitude lat'] = df_rain_stations['N geographic longitude lat'].str.rstrip('º').astype(float)
#df_rain_stations['Altitude above sea level (meters)'] = df_rain_stations['Altitude above sea level (meters)'].astype(int)

df_rain_stations['The opening date'] = pd.to_datetime(df_rain_stations['The opening date'], errors='coerce')
df_rain_stations['The closing date'] = pd.to_datetime(df_rain_stations['The closing date'], errors='coerce')




df_rain_stations.dtypes

station num                                              int64
station name_He                                         object
station name                                            object
station type                                            object
Coordinates on the New Israel Mizrah network             int64
Coordinates on the New Israel North network              int64
E geographic longitude lon                             float64
N geographic longitude lat                             float64
Altitude above sea level (meters)                       object
The opening date                                datetime64[ns]
The closing date                                datetime64[ns]
Data availability period                                object
dtype: object

# Now functions for filtering

### Ate what year did the station first start 
##### default is 1989

In [6]:
def filter_by_opening_date(df, num=1989):
    """
    Filter DataFrame based on 'open date' condition.

    Parameters:
    - df: DataFrame
    - num: Year limit (default is 1989)

    Returns:
    - Filtered DataFrame open before num
    """
    
    
    condition = df['The opening date'].dt.year < num  # Rows where 'open_date' is before the specified year

#Do I really need it?

    # Apply the filter to the DataFrame
    df_filtered = df[condition].copy()  # Using copy to avoid SettingWithCopyWarning

    # Resetting the index might be useful after dropping rows
    df_filtered.reset_index(drop=True, inplace=True)

    return df_filtered

###  Since what year has the station been closed 
##### if it is open in any case it will pass
###### default is 2020

In [7]:
def filter_by_closing_date(df, num=2020):
    """
    Filter DataFrame based on 'closing date' condition.

    Parameters:
    - df: DataFrame
    - num: Year limit (default is 2020)

    Returns:
    - Filtered DataFrame closed not befor num
    """
   

    # Define the conditions after converting to datetime
    condition1 = df['The closing date'].isna()  # Rows where 'closing_date' is NaN
    condition2 = df['The closing date'].dt.year > num  # Rows where 'closing_date' is before the specified year

    # Combine the conditions using the OR operator (|)
    combined_condition = condition1 | condition2
#Do I really need it?
    # Apply the filter to the DataFrame
    df_filtered = df[combined_condition].copy()  # Using copy to avoid SettingWithCopyWarning

    # Resetting the index might be useful after dropping rows
    df_filtered.reset_index(drop=True, inplace=True)

    return df_filtered

# How far south are the stations (North South line)

In [8]:
def filter_by_coordinates_south(df, num=554000):
    """
    Filter DataFrame based on the specified column and value.

    Parameters:
    - df: DataFrame
    - num: Threshold value for filtering (default is 554000)
    - column_index: Index of the column to filter (default is 5)

    Returns:
    - Filtered DataFrame
    """
    

    # Define the condition
    condition = df[df.columns[5]].astype(int) <= num

    # Apply the filter to the DataFrame
    df_filtered = df[condition].copy()  # Using copy to avoid SettingWithCopyWarning

    # Resetting the index might be useful after dropping rows
    df_filtered.reset_index(drop=True, inplace=True)

    return df_filtered

# Allows reading  filter together

In [9]:
def combined_filter_function(df, num_coordinates=554000, num_closing_date=2020,num_avlbol=1989):
    """
    Apply multiple filters to a DataFrame.

    Parameters:
    - df: DataFrame
    - num_coordinates: Threshold value for Coordinates South filtering (default is 554000)
    - num_closing_date: Year limit for closing date filtering (default is 2020)

    Returns:
    - Filtered DataFrame
    """
    
    # First filter by Coordinates South
    df_filtered_coordinates = filter_by_coordinates_south(df, num=num_coordinates)

    # Then filter by closing date
    df_final_filtered = filter_by_closing_date(df_filtered_coordinates, num=num_closing_date)
    
    df_temp = filter_by_opening_date(df_final_filtered)
   
    return df_temp

In [10]:
filtered_df = combined_filter_function(df_rain_stations)

In [12]:
filtered_df.to_csv('Processed Data\meta stations rain.csv')